stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  stage: test
  variables:
    GIT_STRATEGY: none
    CLONE_DIR: "~/pw/auto"
    GITLAB_REPO_URL: "https://gitlab.sh.nextgenwaterprediction.com/Jyoti.Mikkilineni/fim_c_automation.git"
    
  environment: test
  before_script:
    - echo $SSH_KEY
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Deploying FIMC to TEST..."
    # - git config --global url."https://oauth2:${GITLAB_TOKEN}@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY jyoti.mikkilineni@10.203.108.157 "
     pip install pytest && pip install pytest-html && 
     pip install geopandas && rm -rf $CLONE_DIR && 
     mkdir -p $CLONE_DIR && 
     git clone -b $CI_COMMIT_REF_NAME --single-branch $GITLAB_REPO_URL $CLONE_DIR && 
     cd $CLONE_DIR && git checkout $CI_COMMIT_REF_NAME && git config --global user.name jyoti.mikkilineni && git config  --global user.email jyotipriya.mikkilineni@ertcorp.com &&
     ~/.local/bin/pytest ~/pw/auto/scripts/tests -s && 
     git add report.html && git commit -m 'Adding report to the repo' && git config --global push.default matching && git push"   
    - echo "FIMC deployed to TEST"



