stages:
  - build
  - test

job_build:
  stage: build
  script:
    - echo "Building the project"

job_test:
  stage: test
  variables:
    GIT_STRATEGY: none
  environment: test
  before_script:
    - echo $SSH_KEY
    - chmod 400 $SSH_KEY
    - ssh-agent
  script:
    - echo "Deploying FIMC to TEST..."
    - mkdir -p reports
    - echo $GITLAB_USER_LOGIN
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY jyoti.mikkilineni@10.203.98.180 " cd ~ && 
     git init && git checkout $CI_COMMIT_REF_NAME && ~/.local/bin/pytest ~/pw/auto/scripts/tests -s && git add report.html &&    git commit -m 'Adding report file' && git pull && git push && echo $GITLAB_USER_LOGIN && echo $PASS && git push" 
    
    - echo "FIMC deployed to TEST"



